#!/bin/bash
echo "DATABASE_HOST=[$WORDPRESS_DATABASE_HOST]"
echo "DATABASE_NAME=[$WORDPRESS_DATABASE_NAME]"
echo "DATABASE_USER=[$WORDPRESS_DATABASE_USER]"
echo "DATABASE_PORT=[$WORDPRESS_DATABASE_PORT_NUMBER]"
if [ -n "$WORDPRESS_DATABASE_PASSWORD" ]; then
	echo "PASS_SET=YES (length=${#WORDPRESS_DATABASE_PASSWORD})"
else
	echo "PASS_SET=NO"
fi
echo "USERNAME=[$WORDPRESS_USERNAME]"
echo "EMAIL=[$WORDPRESS_EMAIL]"
